### ISSUE TITLE
RuntimeError: CUDA out of memory. How  can I set max_split_size_mb?

### ISSUE THREAD

**Issue by FrankBallo** [SamarShabanCS/ML-udacity#6]

**Comment by SamarShabanCS** [comment]
follow these steps:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:112.00 MiB"

or run the command:
export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512' this works with me

Also note:
if  you want to empty the cache allocated use:
torch.cuda.empty_cache()
